-- Part 2 of Andrew Renshaw's August 2026 vocabulary: synonyms for the tags that have one.
--
-- Generated by `docs/tools/vocabulary/synonyms.py` — do not hand-edit; change the pipeline and
-- re-run. Slice S18b in the backlog.
--
-- `synonyms` is a `text[]` on the tag row, not a table, so this is a data top-up with no schema
-- change that improves two things at once with no code change: forum search folds
-- `name || synonyms` into both its tsvector and trigram paths, and the research-feed classifier
-- matches a tag on its name *or* any synonym. Before this, 11 tags had synonyms.
--
-- 90 of Part 2's 349 preferred terms name a tag; a term that names more than
-- one tag row updates all of them, because the taxonomy repeats a condition across regions by
-- design and each copy should match the same words. That is 95 rows, 115 distinct terms.
--
-- Each UPDATE writes the **union** of what the tag already had and what Part 2 adds — migration
-- 0025 hand-tuned eleven tags against the live corpus and must not be undone.
--
-- What is deliberately NOT loaded, because a wrong synonym silently mis-files content:
--   14 a bare abbreviation — needs a dry run first
--        Osteoarthritis <- oa
--        Osteoarthritis <- djd
--        Rheumatoid arthritis <- ra
--        Psoriatic arthritis <- psa
--        Ankylosing spondylitis <- as
--        Polymyalgia rheumatica <- pmr
--        Myofascial pain syndrome <- mps
--        Degenerative disc disease <- ddd
--        Osteochondritis dissecans <- ocd
--        Femoroacetabular impingement <- fai
--        Greater trochanteric pain syndrome <- gtps
--        Patellofemoral pain syndrome <- pfps
--        Posterior tibial tendon dysfunction <- pttd
--        Carpal tunnel syndrome <- cts
--    2 footnoted in the source
--        Acetabular dysplasia <- ddh
--        Patellofemoral pain syndrome <- runner's knee
--    7 is itself a tag — a merge question
--        Hamstring tendinopathy <- proximal hamstring tendinopathy
--        Subacromial bursitis <- subdeltoid bursitis
--        Disc protrusion <- disc bulge
--        Spondylolysis <- pars defect
--        Hip labral tear <- acetabular labral tear
--        Tarsal tunnel syndrome <- tibial nerve entrapment
--        Subacromial bursitis <- subdeltoid bursitis
--    2 means more than one tag
--        Disc herniation <- herniated disc
--        Disc extrusion <- herniated disc

-- AC joint osteoarthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['acromioclavicular osteoarthritis'] WHERE "id" = '480234d3-8eb7-5617-99b1-28e58ce54b57';--> statement-breakpoint
-- AC joint separation
UPDATE "community"."tags" SET "synonyms" = ARRAY['acromioclavicular separation'] WHERE "id" = '301b9737-04cc-535d-b8fd-1f0fcfb77dba';--> statement-breakpoint
-- Acetabular dysplasia
UPDATE "community"."tags" SET "synonyms" = ARRAY['developmental dysplasia of the hip'] WHERE "id" = '07db3349-313f-5da1-a0c7-ac42ca92ca75';--> statement-breakpoint
-- Acetabular fracture
UPDATE "community"."tags" SET "synonyms" = ARRAY['fracture of acetabulum'] WHERE "id" = 'fd02a9dc-531a-559b-97e3-6cdc9db72025';--> statement-breakpoint
-- Achilles tendinopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['achilles tendinitis', 'achilles tendon disorder'] WHERE "id" = 'e6c47bc8-8424-524c-9a25-e49648bb32b9';--> statement-breakpoint
-- Ankle impingement
UPDATE "community"."tags" SET "synonyms" = ARRAY['ankle impingement syndrome'] WHERE "id" = 'aaf0ff94-2236-5e34-9e99-9d750dae6a36';--> statement-breakpoint
-- Ankylosing spondylitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['ankylosing spondyloarthritis', 'bechterew disease', 'marie-strümpell disease'] WHERE "id" = '8b9aafa4-e0f9-59f4-85b4-cd54b8fb8f90';--> statement-breakpoint
-- Ankylosing spondylitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['ankylosing spondyloarthritis', 'bechterew disease', 'marie-strümpell disease'] WHERE "id" = '697f0bcf-0710-5fbf-be76-de2e1d50d56c';--> statement-breakpoint
-- Ankylosing spondylitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['ankylosing spondyloarthritis', 'bechterew disease', 'marie-strümpell disease'] WHERE "id" = '8e7beea1-4957-5ea0-a923-8a3e8fe53804';--> statement-breakpoint
-- Biceps tendinopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['long-head biceps tendinopathy'] WHERE "id" = '5213dd14-ff26-5546-98cb-dd8daeb2a4b4';--> statement-breakpoint
-- Carpal tunnel syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['median nerve entrapment at wrist'] WHERE "id" = '7b1b70e1-855f-5ebd-bad0-7ec897a29889';--> statement-breakpoint
-- Cervical radiculopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['cervical nerve-root disorder'] WHERE "id" = '27a401d4-6a23-50bd-9eb9-ecf268a6f60f';--> statement-breakpoint
-- Cervical spinal stenosis
UPDATE "community"."tags" SET "synonyms" = ARRAY['cervical canal stenosis'] WHERE "id" = '0babdfcc-a136-5095-968e-5c4d292b0ac4';--> statement-breakpoint
-- Cervical spondylosis
UPDATE "community"."tags" SET "synonyms" = ARRAY['cervical degenerative disease', 'neck spondylosis'] WHERE "id" = 'e5877b4a-cba1-5516-8d1a-0027e0f5364c';--> statement-breakpoint
-- Compression fracture
UPDATE "community"."tags" SET "synonyms" = ARRAY['vertebral compression fracture'] WHERE "id" = '165a3889-f9a8-5d9d-be01-5d8f8cd76e1a';--> statement-breakpoint
-- Compression fracture
UPDATE "community"."tags" SET "synonyms" = ARRAY['vertebral compression fracture'] WHERE "id" = '0dbcb7fa-4585-514c-8c3d-924640b48062';--> statement-breakpoint
-- Cubital tunnel syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['ulnar neuropathy at elbow'] WHERE "id" = '2150e703-63f5-5c49-89d4-85500a1dfd40';--> statement-breakpoint
-- Degenerative disc disease
UPDATE "community"."tags" SET "synonyms" = ARRAY['degenerative intervertebral disc disease'] WHERE "id" = 'a885e65b-f8ce-5045-8c17-881351b0e87f';--> statement-breakpoint
-- Degenerative disc disease
UPDATE "community"."tags" SET "synonyms" = ARRAY['degenerative intervertebral disc disease'] WHERE "id" = '4ce20b70-ff48-579e-9b57-ddfbdd0697f6';--> statement-breakpoint
-- Disc extrusion
UPDATE "community"."tags" SET "synonyms" = ARRAY['extruded disc'] WHERE "id" = '713bff93-c219-546a-922f-f72fc59a74c2';--> statement-breakpoint
-- Disc extrusion
UPDATE "community"."tags" SET "synonyms" = ARRAY['extruded disc'] WHERE "id" = '51a22db7-1728-5c55-bb78-dbb6af5ffdde';--> statement-breakpoint
-- Disc herniation
UPDATE "community"."tags" SET "synonyms" = ARRAY['prolapsed disc', 'ruptured disc', 'slipped disc'] WHERE "id" = 'b15897cb-4773-5c72-b05b-99c14dcba142';--> statement-breakpoint
-- Disc protrusion
UPDATE "community"."tags" SET "synonyms" = ARRAY['protruding disc'] WHERE "id" = 'cf4a0545-4c32-5ee0-9d93-b97472699078';--> statement-breakpoint
-- Femoroacetabular impingement
UPDATE "community"."tags" SET "synonyms" = ARRAY['hip impingement'] WHERE "id" = '08c7abcf-fcd6-56cd-8168-fee8fc1f35c3';--> statement-breakpoint
-- Ganglion cyst
UPDATE "community"."tags" SET "synonyms" = ARRAY['ganglion', 'synovial cyst'] WHERE "id" = '6c1f54f6-1094-5eb5-b4e3-09d02e34367a';--> statement-breakpoint
-- Glenohumeral osteoarthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['shoulder oa'] WHERE "id" = '4fb5da98-cd31-55df-a626-157974ab508c';--> statement-breakpoint
-- Gluteal tendinopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['gluteal tendinosis', 'lateral hip tendinopathy'] WHERE "id" = '191ea03d-c1f6-58cc-85cd-c29780761015';--> statement-breakpoint
-- Greater trochanteric pain syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['lateral hip pain syndrome'] WHERE "id" = '8f2d4ed0-30bc-5bb4-a78f-0ee0842cf9c1';--> statement-breakpoint
-- Hallux rigidus
UPDATE "community"."tags" SET "synonyms" = ARRAY['rigid great toe', 'stiff big toe'] WHERE "id" = 'fcb9fc93-a48b-5d26-b731-84e82c44da76';--> statement-breakpoint
-- Hallux valgus
UPDATE "community"."tags" SET "synonyms" = ARRAY['bunion deformity', 'bunions'] WHERE "id" = '55cf0769-c5bb-5938-b4cc-72640d8cb130';--> statement-breakpoint
-- Hip dysplasia
UPDATE "community"."tags" SET "synonyms" = ARRAY['developmental hip dysplasia'] WHERE "id" = '5c8342ac-ebf7-5f90-b5bf-f7516795e92d';--> statement-breakpoint
-- Hip flexor strain
UPDATE "community"."tags" SET "synonyms" = ARRAY['hip flexor injury', 'iliopsoas strain'] WHERE "id" = '230db451-ca25-5aa3-a401-50dd9a3831da';--> statement-breakpoint
-- Hip flexor strain
UPDATE "community"."tags" SET "synonyms" = ARRAY['hip flexor injury', 'iliopsoas strain'] WHERE "id" = 'b8a89318-6d36-56ce-89cd-6568063aa417';--> statement-breakpoint
-- Hip osteoarthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['hip arthrosis', 'hip oa'] WHERE "id" = 'a19ef187-45be-5787-8a87-05a1a8c7bd07';--> statement-breakpoint
-- Hip osteoarthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['hip arthrosis', 'hip oa'] WHERE "id" = '56bfd1ca-ce34-5a13-9583-6bae23ee6411';--> statement-breakpoint
-- Hoffa's fat pad syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['infrapatellar fat-pad impingement'] WHERE "id" = 'df9347b1-ebf9-5cbb-ad4a-7be0ac894d17';--> statement-breakpoint
-- Iliopsoas bursitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['iliopectineal bursitis'] WHERE "id" = 'e4b7a7e7-ed43-5df3-9a9c-924c19386ab9';--> statement-breakpoint
-- Iliopsoas bursitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['iliopectineal bursitis'] WHERE "id" = '4c7e6983-c23d-5117-ac4f-fe7a1e0d9167';--> statement-breakpoint
-- Infrapatellar bursitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['clergyman''s knee'] WHERE "id" = 'b93fe4c4-7a96-5737-bb5f-8d100ff5736c';--> statement-breakpoint
-- Ischial bursitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['weaver''s bottom', 'weaver''s bursitis'] WHERE "id" = 'b3a4c7cb-13ec-5359-a0d6-7574c9ccfae6';--> statement-breakpoint
-- Knee osteoarthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['knee arthrosis', 'knee oa'] WHERE "id" = '731c885f-a350-5cd4-9989-5e888216a709';--> statement-breakpoint
-- Labral tear
UPDATE "community"."tags" SET "synonyms" = ARRAY['glenoid labral tear'] WHERE "id" = 'a3ebd20c-8d45-5514-b255-e68f20534526';--> statement-breakpoint
-- Lateral ankle sprain
UPDATE "community"."tags" SET "synonyms" = ARRAY['low ankle sprain'] WHERE "id" = '814bb986-5fe8-53d1-9530-5c4656ea1a37';--> statement-breakpoint
-- Lumbar radiculopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['lumbar nerve-root disorder'] WHERE "id" = '1f237c5f-0d53-5e16-953e-96ae897856c9';--> statement-breakpoint
-- Lumbar spinal stenosis
UPDATE "community"."tags" SET "synonyms" = ARRAY['lumbar canal stenosis'] WHERE "id" = '746b55b1-1a1f-548a-9bc7-b8e4cf14f79c';--> statement-breakpoint
-- Metatarsalgia
UPDATE "community"."tags" SET "synonyms" = ARRAY['forefoot pain', 'metatarsal pain'] WHERE "id" = '261173de-cd86-5347-8157-4336d45fa29a';--> statement-breakpoint
-- Morton's neuroma
UPDATE "community"."tags" SET "synonyms" = ARRAY['interdigital neuroma', 'morton''s metatarsalgia'] WHERE "id" = '10871fe8-bbf0-51a8-81cc-4b9829c8ed88';--> statement-breakpoint
-- Muscle strain
UPDATE "community"."tags" SET "synonyms" = ARRAY['muscle injury', 'muscular strain'] WHERE "id" = 'ca7d328c-8ee6-578f-a80a-750086c052f1';--> statement-breakpoint
-- Muscle tear
UPDATE "community"."tags" SET "synonyms" = ARRAY['muscle fibre tear', 'muscular tear'] WHERE "id" = '15bc7d50-246a-5802-9d84-93b9b1698e06';--> statement-breakpoint
-- Myofascial pain syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['myofascial', 'myofascial pain', 'trigger point', 'trigger-point pain syndrome'] WHERE "id" = '1b011753-51fe-588f-8838-e72b073789e8';--> statement-breakpoint
-- Myofascial pain syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['myofascial', 'myofascial pain', 'trigger point', 'trigger-point pain syndrome'] WHERE "id" = 'e77534b8-4003-505b-8fa8-bec316e68b7d';--> statement-breakpoint
-- Myofascial pain syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['myofascial', 'myofascial pain', 'trigger point', 'trigger-point pain syndrome'] WHERE "id" = 'c9c06e09-2f90-5155-9e45-64fd6bd016e9';--> statement-breakpoint
-- Olecranon bursitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['student''s elbow'] WHERE "id" = 'edd226f9-6107-5ca9-97a7-89453aafe9be';--> statement-breakpoint
-- Osteoarthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['arthrosis', 'degenerative arthritis', 'degenerative joint disease', 'osteoarthrosis'] WHERE "id" = '10f3df07-5f4a-5ca2-a16a-fa51a9fbfd48';--> statement-breakpoint
-- Osteochondral lesion
UPDATE "community"."tags" SET "synonyms" = ARRAY['cartilage-bone lesion', 'osteochondral', 'osteochondral defect', 'osteochondritis dissecans'] WHERE "id" = '775c2d16-7ede-5801-987f-74bb6e931dcb';--> statement-breakpoint
-- Osteochondritis dissecans
UPDATE "community"."tags" SET "synonyms" = ARRAY['osteochondral fragmentation'] WHERE "id" = '7d9d5ca0-ab75-5ece-97f7-ad2e072a3646';--> statement-breakpoint
-- Patellar dislocation
UPDATE "community"."tags" SET "synonyms" = ARRAY['kneecap dislocation'] WHERE "id" = '8382027a-f7ec-5f35-bde3-eded0e4c52aa';--> statement-breakpoint
-- Patellar instability
UPDATE "community"."tags" SET "synonyms" = ARRAY['kneecap instability', 'patellar dislocation tendency'] WHERE "id" = '9fbf1502-f994-50b6-bde7-e0b6feb7d3ba';--> statement-breakpoint
-- Patellar tendinopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['jumper''s knee', 'patellar tendinitis'] WHERE "id" = '63bfceaf-4e01-55c1-8d66-438ef040a31c';--> statement-breakpoint
-- Patellofemoral pain syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['patellofemoral syndrome'] WHERE "id" = '0816f411-c233-52e2-bd7f-9f5ea9d17315';--> statement-breakpoint
-- Peroneal tendinopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['fibularis tendinopathy'] WHERE "id" = '61e1dec2-321d-58e6-9443-48b648a79f78';--> statement-breakpoint
-- Pes anserine bursitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['pes anserinus bursitis'] WHERE "id" = '31a530c9-c962-53d0-a71e-4631e1ebef90';--> statement-breakpoint
-- Polymyalgia rheumatica
UPDATE "community"."tags" SET "synonyms" = ARRAY['polymyalgia'] WHERE "id" = '5430cfe4-9bea-57f3-a968-e63a02ecb893';--> statement-breakpoint
-- Posterior tibial tendon dysfunction
UPDATE "community"."tags" SET "synonyms" = ARRAY['tibialis posterior tendon dysfunction'] WHERE "id" = '56b9b247-ee60-5df8-81aa-bc1035fa597c';--> statement-breakpoint
-- Prepatellar bursitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['housemaid''s knee'] WHERE "id" = 'ede0d42f-bf0d-5d68-9dec-93c8aabe90b7';--> statement-breakpoint
-- Psoriatic arthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['psoriatic arthropathy'] WHERE "id" = '612276ed-02d5-5554-af51-990b6edad8a1';--> statement-breakpoint
-- Psoriatic arthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['psoriatic arthropathy'] WHERE "id" = 'e8c6c1b9-0f5e-5f00-bb55-d96a0109c931';--> statement-breakpoint
-- Psoriatic arthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['psoriatic arthropathy'] WHERE "id" = 'e88c82d5-4c5c-5e7e-b192-c7a5c9b5f0a1';--> statement-breakpoint
-- Rheumatoid arthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['rheumatoid disease', 'rheumatoid polyarthritis'] WHERE "id" = 'a8048cc2-9f0e-5431-b133-2525a17bbcb9';--> statement-breakpoint
-- Rheumatoid arthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['rheumatoid disease', 'rheumatoid polyarthritis'] WHERE "id" = '7e60af28-a28e-5eef-94a5-9650f41a06b9';--> statement-breakpoint
-- Rheumatoid arthritis
UPDATE "community"."tags" SET "synonyms" = ARRAY['rheumatoid disease', 'rheumatoid polyarthritis'] WHERE "id" = 'e5e066fb-754a-54ad-8760-739e7a3b5983';--> statement-breakpoint
-- Rotator cuff tendinopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['rotator cuff tendinitis'] WHERE "id" = 'dbbaf824-c202-5f9c-881c-49e9e1abef59';--> statement-breakpoint
-- SLAP lesion
UPDATE "community"."tags" SET "synonyms" = ARRAY['superior labral anterior-to-posterior lesion'] WHERE "id" = '308e8a7b-d629-5b0d-971b-d15b2faab88e';--> statement-breakpoint
-- Sacroiliac joint dysfunction
UPDATE "community"."tags" SET "synonyms" = ARRAY['sacroiliac joint disorder', 'sij dysfunction'] WHERE "id" = 'b5dc46f9-11ee-54cd-9c98-7155a1747b60';--> statement-breakpoint
-- Sacroiliac joint dysfunction
UPDATE "community"."tags" SET "synonyms" = ARRAY['sacroiliac joint disorder', 'sij dysfunction'] WHERE "id" = '9ebadacf-fa74-53d6-b54c-b13894f552b5';--> statement-breakpoint
-- Sacroiliitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['sacroiliac joint inflammation', 'si-joint inflammation'] WHERE "id" = '344bb682-8fbe-519e-929f-fbb99903abdb';--> statement-breakpoint
-- Sacroiliitis
UPDATE "community"."tags" SET "synonyms" = ARRAY['sacroiliac joint inflammation', 'si-joint inflammation'] WHERE "id" = '0b2a75ef-7b2b-58a0-87f9-68121a843fc2';--> statement-breakpoint
-- Scapular dyskinesis
UPDATE "community"."tags" SET "synonyms" = ARRAY['scapular movement dysfunction'] WHERE "id" = '05ac1444-e8b7-5cd2-94ae-c350ea54335c';--> statement-breakpoint
-- Sciatica
UPDATE "community"."tags" SET "synonyms" = ARRAY['sciatic neuralgia', 'sciatic pain'] WHERE "id" = '3938764b-65a2-5ff7-a3fb-3bbbe6d69ebc';--> statement-breakpoint
-- Scoliosis
UPDATE "community"."tags" SET "synonyms" = ARRAY['lateral spinal curvature', 'spinal curvature'] WHERE "id" = 'c96fdb6a-459e-5bf1-8584-bbe542cb74cb';--> statement-breakpoint
-- Shoulder dislocation
UPDATE "community"."tags" SET "synonyms" = ARRAY['glenohumeral dislocation'] WHERE "id" = '28879a7a-9e35-57cd-aa4c-a61371c4572e';--> statement-breakpoint
-- Shoulder instability
UPDATE "community"."tags" SET "synonyms" = ARRAY['glenohumeral instability'] WHERE "id" = '909ad48d-a636-5e87-8dea-3104418c37ca';--> statement-breakpoint
-- Shoulder subluxation
UPDATE "community"."tags" SET "synonyms" = ARRAY['glenohumeral subluxation'] WHERE "id" = '0dded601-5353-5401-a492-381e4e7035ce';--> statement-breakpoint
-- Snapping hip syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['coxa saltans'] WHERE "id" = '926d1351-9365-5762-b852-d07a4d35b713';--> statement-breakpoint
-- Snapping scapula syndrome
UPDATE "community"."tags" SET "synonyms" = ARRAY['scapulothoracic bursitis'] WHERE "id" = 'a303ab4b-8dc5-5013-94b6-ae2dee5dfd9e';--> statement-breakpoint
-- Spondylolisthesis
UPDATE "community"."tags" SET "synonyms" = ARRAY['slipped vertebra', 'vertebral slippage'] WHERE "id" = '1ad18e84-99ec-553c-9a4e-8f091b3b7399';--> statement-breakpoint
-- Spondylolysis
UPDATE "community"."tags" SET "synonyms" = ARRAY['pars interarticularis defect'] WHERE "id" = 'a52c3d86-dd8c-5bd9-8b0b-f8680223a0c3';--> statement-breakpoint
-- Spondylosis
UPDATE "community"."tags" SET "synonyms" = ARRAY['degenerative spinal disease', 'spinal osteoarthritis'] WHERE "id" = 'e8066411-010b-53c7-ae93-314de9f34921';--> statement-breakpoint
-- Stress fracture
UPDATE "community"."tags" SET "synonyms" = ARRAY['fatigue fracture', 'stress injury'] WHERE "id" = 'adc209e2-4f21-5071-9314-811e7d4e35e4';--> statement-breakpoint
-- Stress fracture
UPDATE "community"."tags" SET "synonyms" = ARRAY['fatigue fracture', 'stress injury'] WHERE "id" = 'b9ebae4c-7390-5849-a18f-f7765aadc9d8';--> statement-breakpoint
-- Stress fracture
UPDATE "community"."tags" SET "synonyms" = ARRAY['fatigue fracture', 'stress injury'] WHERE "id" = '7ebbd2e0-07f0-5024-9d25-1ee3e628f8e8';--> statement-breakpoint
-- TFCC injury
UPDATE "community"."tags" SET "synonyms" = ARRAY['triangular fibrocartilage complex injury'] WHERE "id" = 'f99e5f14-617b-5615-ab8f-837c21f0212d';--> statement-breakpoint
-- Tendinopathy
UPDATE "community"."tags" SET "synonyms" = ARRAY['tendon disease', 'tendon disorder'] WHERE "id" = 'de1e7166-54b6-5cfa-9fb3-646781fc71f6';--> statement-breakpoint
-- Trigger finger
UPDATE "community"."tags" SET "synonyms" = ARRAY['stenosing tenosynovitis'] WHERE "id" = '511aabf7-9bf6-5dd7-97d6-37f821bdcca4';--> statement-breakpoint
-- Wrist sprain
UPDATE "community"."tags" SET "synonyms" = ARRAY['wrist ligament injury'] WHERE "id" = 'b2e53668-8abb-584b-b553-7979de62bf06';--> statement-breakpoint
