# fly.toml app configuration file generated for askapeer-research-feed on 2026-07-13T10:23:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'askapeer-research-feed'
primary_region = 'lhr'

[build]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
